export var MarkerType;
(function (MarkerType) {
    MarkerType[MarkerType["MarkerTypeUpsideDownCone"] = 0] = "MarkerTypeUpsideDownCone";
    MarkerType[MarkerType["MarkerTypeVerticalCylinder"] = 1] = "MarkerTypeVerticalCylinder";
    MarkerType[MarkerType["MarkerTypeThickChevronUp"] = 2] = "MarkerTypeThickChevronUp";
    MarkerType[MarkerType["MarkerTypeThinChevronUp"] = 3] = "MarkerTypeThinChevronUp";
    MarkerType[MarkerType["MarkerTypeCheckeredFlagRect"] = 4] = "MarkerTypeCheckeredFlagRect";
    MarkerType[MarkerType["MarkerTypeCheckeredFlagCircle"] = 5] = "MarkerTypeCheckeredFlagCircle";
    MarkerType[MarkerType["MarkerTypeVerticleCircle"] = 6] = "MarkerTypeVerticleCircle";
    MarkerType[MarkerType["MarkerTypePlaneModel"] = 7] = "MarkerTypePlaneModel";
    MarkerType[MarkerType["MarkerTypeLostMCDark"] = 8] = "MarkerTypeLostMCDark";
    MarkerType[MarkerType["MarkerTypeLostMCLight"] = 9] = "MarkerTypeLostMCLight";
    MarkerType[MarkerType["MarkerTypeNumber0"] = 10] = "MarkerTypeNumber0";
    MarkerType[MarkerType["MarkerTypeNumber1"] = 11] = "MarkerTypeNumber1";
    MarkerType[MarkerType["MarkerTypeNumber2"] = 12] = "MarkerTypeNumber2";
    MarkerType[MarkerType["MarkerTypeNumber3"] = 13] = "MarkerTypeNumber3";
    MarkerType[MarkerType["MarkerTypeNumber4"] = 14] = "MarkerTypeNumber4";
    MarkerType[MarkerType["MarkerTypeNumber5"] = 15] = "MarkerTypeNumber5";
    MarkerType[MarkerType["MarkerTypeNumber6"] = 16] = "MarkerTypeNumber6";
    MarkerType[MarkerType["MarkerTypeNumber7"] = 17] = "MarkerTypeNumber7";
    MarkerType[MarkerType["MarkerTypeNumber8"] = 18] = "MarkerTypeNumber8";
    MarkerType[MarkerType["MarkerTypeNumber9"] = 19] = "MarkerTypeNumber9";
    MarkerType[MarkerType["MarkerTypeChevronUpx1"] = 20] = "MarkerTypeChevronUpx1";
    MarkerType[MarkerType["MarkerTypeChevronUpx2"] = 21] = "MarkerTypeChevronUpx2";
    MarkerType[MarkerType["MarkerTypeChevronUpx3"] = 22] = "MarkerTypeChevronUpx3";
    MarkerType[MarkerType["MarkerTypeHorizontalCircleFat"] = 23] = "MarkerTypeHorizontalCircleFat";
    MarkerType[MarkerType["MarkerTypeReplayIcon"] = 24] = "MarkerTypeReplayIcon";
    MarkerType[MarkerType["MarkerTypeHorizontalCircleSkinny"] = 25] = "MarkerTypeHorizontalCircleSkinny";
    MarkerType[MarkerType["MarkerTypeHorizontalCircleSkinny_Arrow"] = 26] = "MarkerTypeHorizontalCircleSkinny_Arrow";
    MarkerType[MarkerType["MarkerTypeHorizontalSplitArrowCircle"] = 27] = "MarkerTypeHorizontalSplitArrowCircle";
    MarkerType[MarkerType["MarkerTypeDebugSphere"] = 28] = "MarkerTypeDebugSphere";
    MarkerType[MarkerType["MarkerTypeDallorSign"] = 29] = "MarkerTypeDallorSign";
    MarkerType[MarkerType["MarkerTypeHorizontalBars"] = 30] = "MarkerTypeHorizontalBars";
    MarkerType[MarkerType["MarkerTypeWolfHead"] = 31] = "MarkerTypeWolfHead";
})(MarkerType || (MarkerType = {}));
//# sourceMappingURL=marker.type.js.map